version: "3.9"
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080" 
    environment:
      - MONGO_URI=mongodb://mongo:27017/EmployeeDb 
    depends_on:
      - mongo

  frontend:
    build:
      context: ./Frontend
    ports:
      - "4200:80" 
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
